// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKN9lwEyf3FxSzxqeeNauW_nIfjlSkW0I',
    appId: '1:950053557474:web:48099f4f8574930e8f3abb',
    messagingSenderId: '950053557474',
    projectId: 'opal1-1',
    authDomain: 'opal1-1.firebaseapp.com',
    storageBucket: 'opal1-1.appspot.com',
    measurementId: 'G-01KXKXGPWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhd-Sg3oNFDrAANMPSHBoCq7_5JciDgY8',
    appId: '1:950053557474:android:f9d303376f7525828f3abb',
    messagingSenderId: '950053557474',
    projectId: 'opal1-1',
    storageBucket: 'opal1-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJzOjQRLHgyvKmqzThUIDO2Lw47ZMY2fc',
    appId: '1:950053557474:ios:cb4a969d357feda78f3abb',
    messagingSenderId: '950053557474',
    projectId: 'opal1-1',
    storageBucket: 'opal1-1.appspot.com',
    iosBundleId: 'com.example.opal11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJzOjQRLHgyvKmqzThUIDO2Lw47ZMY2fc',
    appId: '1:950053557474:ios:87a1293087b6e0348f3abb',
    messagingSenderId: '950053557474',
    projectId: 'opal1-1',
    storageBucket: 'opal1-1.appspot.com',
    iosBundleId: 'com.example.opal11.RunnerTests',
  );
}
